version: '3'
networks:
  asmoro-network:
    driver: bridge
services:
  asmorobe:
    image: "haritsrizkal/asmorobe:0.1.4"
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - asmoro-network
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3305"
    environment:
      - "MYSQL_ROOT_HOST=root"
      - "MYSQL_ROOT_PASSWORD=asmoro123"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=asmoro123"
      - "MYSQL_DATABASE=recipedb"  
    volumes:
      - "volmysql:/var/lib/mysql"
    networks:
      - asmoro-network
volumes:
  volmysql: 
    driver: azure_file
    driver_opts:
      share_name: asmoro-mysql
      storage_account_name: recipestorageaccount
  
