version: '3'
networks:
  asmoro-network:
    driver: bridge
services:
  asmorobe:
    image: "haritsrizkal/asmorobe:0.0.5"
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - asmoro-network
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_HOST=root"
      - "MYSQL_ROOT_PASSWORD=asmoro123"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=asmoro123"
      - "MYSQL_DATABASE=recipedb"  
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./database/pokemon.sql:/docker-entrypoint-initdb.d/pokemon.sql"
    networks:
      - "asmoro-network"
  
